language: php
php:
  - 7.2
env:
  - APP_ENV=testing APP_DEBUG=true APP_KEY=29e40da44d41863b92575171ba0996ca8c734898de20014b69979fe98de7ca07 APP_TIMEZONE=UTC DB_CONNECTION=pgsql DB_DATABASE=huitzilopochtli_test DB_USERNAME=postgres CACHE_DRIVER=file QUEUE_DRIVER=sync
before_install: 
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
install:
  - composer install
before_script:
  - psql -c 'create database huitzilopochtli_test;' -U postgres
script:
  - vendor/bin/phpunit --coverage-clover=coverage.xml
after_success:
  - ./cc-test-reporter --coverage-report=coverage.xml
  - bash <(curl -s https://codecov.io/bash)
