language: php
php:
  - 5.6
env:
  - APP_ENV=testing APP_DEBUG=true APP_KEY=29e40da44d41863b92575171ba0996ca8c734898de20014b69979fe98de7ca07 APP_TIMEZONE=UTC DB_CONNECTION=pgsql DB_DATABASE=huitzilopochtli_test DB_USERNAME=postgres CACHE_DRIVER=file QUEUE_DRIVER=sync
install:
  - composer install
before_script:
  - psql -c 'create database huitzilopochtli_test;' -U postgres
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build
script:
  - vendor/bin/phpunit --coverage-clover=coverage.xml
after_success:
  - bash <(curl -s https://codecov.io/bash)
after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
